BankingProject-main/final/bank/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from accounts import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^accounts/', include("accounts.urls")),
    url(r'^profiles/', include("profiles.urls"))
]

BankingProject-main/final/profiles/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = "profiles"

urlpatterns = [
    #path(r"account_status", views.show_account_status, name = "account_status"),
    #url(r"^login/$", views.sign_in, name = "signin"),
    #url(r"^logout/$", views.logout_view, name = "logout"),
    #url(r"^test/$", views.test_classes, name = "test_class"),
    path(r"dashboard", views.display_menu, name = "dashboard"),
    path(r"redirect_from_dashboard", views.get_function_chosen, name = "get_function_chosen"),
    path(r"account_management", views.account_management, name='account_management'),
    path(r"process_account_action", views.get_account_action, name='get_account_action'),
    path(r"withdraw", views.withdraw, name='withdraw'),
    path(r"deposit", views.deposit, name='deposit'),
    path(r"stat_gen", views.stat_gen, name='stat_gen'),
    path(r"get_stat_gen", views.get_transaction_action, name='get_transaction_action'),
    path(r"show_ecs_options", views.show_ecs_options, name='show_ecs_options'),
    path(r"redirect_ecs", views.redirect_ecs, name='redirect_ecs'),
    path(r"start_ecs", views.start_ecs, name='start_ecs'),
    path(r"store_new_ecs_data", views.store_new_ecs_data, name='store_new_ecs_data'),
    path(r"show_due_bills", views.show_due_bills, name='show_due_bills'),
    path(r"pay_bill", views.pay_bill, name='pay_bill'),
]

BankingProject-main/final/profiles/models.py
from django.db import models

# Create your models here.
class Customer_Data(models.Model):
    Cust_ID = models.AutoField(primary_key=True)
    Name = models.CharField(max_length=200)
    Phone_no = models.CharField(max_length=10)
    #Fixed length can't be specified. Only max_length can be.
    Email = models.EmailField()
    #Username = models.CharField(max_length=30)
    #Password = models.CharField(max_length=30)
    class Meta:
        db_table = 'customer'
   
class Account_Data(models.Model):
    Accno = models.IntegerField(primary_key=True)
    Owner = models.ForeignKey(Customer_Data, on_delete=models.CASCADE)
    Balance = models.FloatField()
    #Name = models.CharField(max_length=200)
    class Meta:
        db_table = 'account'
'''    
class Deposits(models.Model): 
    Trans_ID = models.AutoField(primary_key=True)
    Accno = models.ForeignKey(Account, on_delete=models.CASCADE)
    Amount = models.FloatField()
    class Meta:
        db_table = 'deposits'
        
class Withdraws(models.Model): 
    Trans_ID = models.AutoField(primary_key=True)
    Accno = models.ForeignKey(Account, on_delete=models.CASCADE)
    Amount = models.FloatField()
    class Meta:
        db_table = 'withdraws' 
'''

class Transactions(models.Model): 
    Trans_ID = models.AutoField(primary_key=True)
    Accno = models.ForeignKey(Account_Data, on_delete=models.CASCADE)
    Amount = models.FloatField()
    Type = models.CharField(max_length=30)
    #Type can be "withdraw" or "deposit"
    class Meta:
        db_table = 'transactions'
        
class Money_Transfers(models.Model):             
    Trans_ID = models.AutoField(primary_key=True)
    From_accno = models.ForeignKey(Account_Data, on_delete=models.CASCADE, related_name = 'From_accno')
    To_accno = models.ForeignKey(Account_Data, on_delete=models.CASCADE, related_name = 'To_accno')
    Amount = models.FloatField()
    class Meta:
        db_table = 'transfers'
    
    
        
class ECS_Data(models.Model):
    ECS_ID = models.AutoField(primary_key=True)
    Payer_Name = models.CharField(max_length=300)
    Upper_Limit = models.FloatField()
    Account = models.ForeignKey(Account_Data, on_delete=models.CASCADE)
    class Meta:
        db_table = 'ecs'
    
class Bills(models.Model):
    #id column created implicitly
    ECS_ID = models.ForeignKey(ECS_Data, on_delete=models.CASCADE)
    Amount = models.FloatField()
    Completed = models.BooleanField()
    class Meta:
        db_table = 'bills'        
    

BankingProject-main/final/profiles/views.py
#sys.path defines paths from which imports can be made

import sys, os
print(os.getcwd())
sys.path.append(os.getcwd()+'/profiles/utils')

from django.shortcuts import render, redirect
from profiles.models import Customer_Data, Account_Data,Transactions,ECS_Data,Bills
import random
from django.http import HttpResponse
import Classes

cur_customer = None #Stores customer obj

# Create your views here.
def randomGen():
    # return a 6 digit random number
    return int(random.uniform(100000, 999999))

def display_menu(request):
    global cur_customer
    user_log_in = Classes.Login_Details(request.user.username, request.user.password)
    #Check if customer is a new or existing customer
    cust_details = Customer_Data.objects.filter(Name = user_log_in.username)
    print("cust_details", cust_details)
    if(cust_details):
       print("Existing Customer")
       customer = Classes.Customer(user_log_in)
       print("customer obj", customer)
    else:
        print("Making New Customer")
        customer = Classes.New_Customer(user_log_in, user_log_in.username, '9999999999', 'saa@gmail.com')
    print("Customer name:", customer.customer_data.Name)
    cur_customer = customer
    return render(request, 'profiles/user_account.html', 
    {'customer':customer})
  
def account_management(request):
    accounts = cur_customer.accounts
    user_accnos = list(accounts.keys())
    print("user_accnos", user_accnos)
    return render(request, 'profiles/account_details.html', 
    {'customer':cur_customer, 'accounts':accounts, 'can_close_accnos':user_accnos})


def withdraw(request):
    accounts = cur_customer.accounts
    msg="<br>Enter a valid account no. and also check for ur balance!</p><br>"
    if request.method == "POST":
        acc_num=int(request.POST.get('acc_no'))
        amount=int(request.POST.get('amount'))
        print('requestPOST=',acc_num,type(acc_num))
        #print('account dict:',accounts.keys())
        if acc_num in accounts:
            #acc_obj= accounts[acc_num]
            acc_q=Account_Data.objects.get(Accno=acc_num)
            balance=acc_q.Balance
            print("balance:",balance)
            if(balance>=amount):
                trans=Classes.Account(acc_q)
                trans.create_transaction(amount,"withdraw")
                balance-=amount
                acc_q.Balance=balance
                print("balance:",acc_q.Balance)
                acc_q.save()
                cur_customer.accounts[acc_num].account_details.Balance-=amount
                msg="<td>Withdrawn Successfully!</td><br>"
            else:
                msg="<td>Not sufficient balance!</td><br>"
            
        else:
            msg="<p>Invalid account number</p><br>"
    return render(request, 'profiles/withdraw.html',{'customer':cur_customer, 'accounts':accounts,'msg':msg})
    #'customer':cur_customer, 'accounts':accounts

def deposit(request):
    accounts = cur_customer.accounts
    msg="<br>Enter a valid account no. and also check for ur balance!</p><br>"
    if request.method == "POST":
        acc_num=int(request.POST.get('acc_no'))
        amount=int(request.POST.get('amount'))
        print('requestPOST=',acc_num,type(acc_num))
        #print('account dict:',accounts.keys())
        if acc_num in accounts:
            #acc_obj= accounts[acc_num]
            acc_q=Account_Data.objects.get(Accno=acc_num)
            balance=acc_q.Balance
            print("balance:",balance)
            trans=Classes.Account(acc_q)
            trans.create_transaction(amount,"deposit")
            balance+=amount
            acc_q.Balance=balance
            print("balance:",acc_q.Balance)
            acc_q.save()
            cur_customer.accounts[acc_num].account_details.Balance+=amount
            msg="<td>Deposited Successfully!</td><br>"
        else:
            msg="<p>Invalid account number</p><br>"
    return render(request, 'profiles/deposit.html',{'customer':cur_customer, 'accounts':accounts,'msg':msg})

def stat_gen(request):
    accounts = cur_customer.accounts
    print(accounts)
    msg=""
    all_transactions = {}
    for acc in accounts:
        print("acc_no:",acc)
        acc_q=Account_Data.objects.get(Accno=int(acc))
        trans=Classes.Account(acc_q)
        #trans_rec=Transactions.objects.filter(Accno_id=int(acc))
        #print("trans_rec:",trans_rec)
        transaction=trans.get_transaction_log()
        trans_objs_list = list(transaction.values())
        all_transactions[acc] = all_transactions.get(acc, [])+trans_objs_list
        print("trans:",transaction)
    return render(request, 'profiles/stat_gen.html',{'customer':cur_customer, 'accounts':accounts, 'transaction':all_transactions,'msg':msg})

def get_transaction_action(request):
    accounts = cur_customer.accounts
    print("got:", request.GET)
    msg="filter"
    button_action = request.GET['account_action']
    all_transactions = {}
    if(button_action == 'withdraw'):
        for acc in accounts:
            transaction=Transactions.objects.filter(Accno_id=int(acc),Type="withdraw")
            print("withdraw:",transaction)
            all_transactions[acc] = list(transaction)
    elif(button_action == 'deposit'):
        for acc in accounts:
            transaction=Transactions.objects.filter(Accno_id=int(acc),Type="deposit")
            all_transactions[acc] = list(transaction)
    elif(button_action == 'all'):
        return redirect('profiles:stat_gen')
    #print("Account created successfully")
    print("all_trans:", all_transactions)
    return render(request,'profiles/stat_gen.html',{'customer':cur_customer, 'accounts':accounts, 'transaction':all_transactions,'msg':msg});

def get_function_chosen(request):
    print(request.GET) 
    #print("Got menu") 
    menu_chosen = request.GET['function_chosen']
    if(menu_chosen=='view_accounts'):
        return redirect('profiles:account_management') #name of view given in urls.py
    elif(menu_chosen=='withdraw'):
        return redirect('profiles:withdraw') #name of view given in urls.py
    elif(menu_chosen=='deposit'):
        return redirect('profiles:deposit') #name of view given in urls.py
    elif(menu_chosen=='stat_gen'):
        return redirect('profiles:stat_gen') #name of view given in urls.py
    elif(menu_chosen=='start_ecs'):
        return redirect('profiles:show_ecs_options')
    
def get_account_action(request):
    print("got:", request.GET)
    account_action = request.GET['account_action']
    #err_msg=""
    if(account_action == 'create'):
        cur_customer.create_account()
    elif(account_action == 'close'):
        print(request.GET)
        print("account:", cur_customer.accounts)
        close_accno = int(request.GET['close_accno'])
        #if(close_accno not in accounts):
        #    err_msg = "Invalid Account number!"
        #else:
        cur_customer.close_account(close_accno)
    else:
        print("Got neither create nor close")
    #print("Account created successfully")
    return redirect('profiles:account_management')

def show_ecs_options(request):
    return render(request, "profiles/ecs.html")
    
def redirect_ecs(request):
    ecs_option = request.GET['ecs_option']
    print("ecs_option", ecs_option)
    if(ecs_option == "new_ecs"):
        return redirect('profiles:start_ecs')
    if(ecs_option == 'view_ecs'):
        return redirect('profiles:show_due_bills')
        
def start_ecs(request):
    msg=""
    return render(request, 'profiles/set_up_ecs.html', {"msg":msg})
    
def store_new_ecs_data(request):
    #Make a class for ECS
    payer_name = request.GET['payer_name']
    upper_limit = request.GET['upper_limit']
    accno = int(request.GET['accno'])
    acc_obj = cur_customer.accounts[accno]
    ecs_obj = Classes.New_ECS(payer_name, acc_obj, upper_limit)
    msg = "New ECS Created Successfully!"
    return render(request, 'profiles/set_up_ecs.html', {"msg":msg})
    
def show_due_bills(request):
    accounts = cur_customer.accounts
    bills_list = []
    for acc_obj in accounts.values():
        ecs_list = ECS_Data.objects.filter(Account = acc_obj.account_details)
        for ecs in ecs_list:
            bills_for_cur_ecs = Bills.objects.filter(ECS_ID = ecs).filter(Completed = False)
            for bill in bills_for_cur_ecs:
                bill_details = [bill.id, ecs.Payer_Name, acc_obj.account_no, bill.Amount, ecs.Upper_Limit]
                if(bill.Amount<=ecs.Upper_Limit):
                    bill_details.append("yes")
                else:
                    bill_details.append("NO")
                #bills_list.extend(list(bills_for_cur_ecs))
                bills_list.append(bill_details)
    print(bills_list)
    return render(request, 'profiles/ecs_show_bills.html', {'bills_list':bills_list});
    
def pay_bill(request):
    bill_id = request.GET['bill_id']
    print("bill_id", bill_id)
    bill_obj = Bills.objects.get(id=bill_id);
    bill_obj.Completed = True
    bill_obj.save()
    return redirect('profiles:show_due_bills')
           
'''    
def test_classes(request):
    print("got to test classes")
    login_obj = Classes.Login_Details('anj', 'anj123')
    cust_obj = Classes.Customer(login_obj)
    acc_obj = Classes.Account(1111)
    new_acc_obj = Classes.New_Account(111, cust_obj)
    new_cust_obj = Classes.New_Customer(login_obj, 'anjali', 'addr1', '99880')
'''    
    

        

BankingProject-main/final/profiles/templates/profiles/account_details.html

<body>

    {% extends 'base.html' %}
    
    {% block stylecontent %}
    <style>
        body {
            background-color: aliceblue;
        }
        h2 {
            font-family: 'Slabo 27px';
            border-bottom: 1px solid black;
            font-weight: 900;
        }
        #page_name {
            font-size: 25;
        }
        
        #details_box {
            font-size: 23;
            top: 50px;
            left: 30px;
        }
        
        #details_table {
            font-size: 20;
            position: relative;
            align-items: center;
        }
        
        #edit_details {
            top: 10px;
            left: 20px;
        }
        
        #edit_button {
            border: none;
            color: black;
            padding: 5px 7px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 14px;
            margin: 2px 1px;
            cursor: pointer;
        }
    </style>
    {%endblock%}
    
    {% block bodycontent %}
        {% csrf_token %}
        {% if user.is_authenticated %}
         <form name="acc_management" id="acc_management" action="process_account_action"> 
            <input type="hidden" name="account_action" id="account_action">  
            <table width=70% height=60%>
                <tr>
                    <td>
        
                        <div id="page_name" style="float:left;">
                            <font color="#3399ff">Welcome {{ customer.customer_data.Name }}!</font>
                        </div>
                    </td>
                    <td>
                        <div id="edit_details" style="float:right;">
                            <button type="button" id="edit_button"><a href="{% url 'profiles:dashboard' %}">Home</a></button>
                        </div>
                    </td>
                </tr>
        
        
        
                <tr>
                    <td>
                        <div id="details_box" align="center">
                            <h4>Account Details :</h4>
                            <table id="details_table" cellpadding=5px;>
                                <tr>
                                    <td>Customer Name: {{ customer.customer_data.Name }}</td>
                                    
                                </tr>
                                <tr>
                                    <td>Branch-ID: <span id="branch-id">AF600_ElectronicCity</span> </td>
                                </tr>
                                {% if accounts %}
                                {% for accno, acc_obj in accounts.items %}
                                <tr>
                                    <td>Account number : {{ accno }}</td>
                                </tr>
                                <tr>
                                    <td>Balance: {{ acc_obj.account_details.Balance }}</td>
                                    
                                </tr>
                                {% endfor %}
                                {% else %}
                                <tr> <td> New Customer. No accounts yet. </td></tr>
                                {% endif %}
                            </table>
                        </div>
                    </td>
                </tr>
            </table>
        
        {% else %}
            <p>Welcome, new user. Please log in.</p>
        {% endif %}
        
        <button onclick="set_account_action('create')"> Create New Account </button> <br>
        Close Account?
        <input name="close_accno" id="close_accno">
        <button onclick="set_account_action('close');check_valid_accno()" type="button"> Close Account </button>
        <!-- Setting button type = "button" so that form does not submit on button click -->
        <span id="err_msg"> <b> </b> </span>
        </form>
        <script>
        function set_account_action(account_action_val){
            hidden_field = document.getElementById("account_action");
            hidden_field.setAttribute("value", account_action_val);
         }
         
         function check_valid_accno(){
            accno = document.getElementById("close_accno").value;
            accno_int = parseInt(accno)
            valid_accounts = {{can_close_accnos}};
            invalid_accno = true;
            
            for(accno of valid_accounts){
                if(accno_int == accno){
                    form_elem = document.getElementById("acc_management");
                    form_elem.submit();
                    invalid_accno = false;
                }
            }
            
            if(invalid_accno){
                err_msg_tag = document.getElementById("err_msg");
                err_msg_tag.textContent = "Invalid Account Number! User does not own this account";
            }
            /*
            if(accno_int in valid_accounts){
            //Checking if accno exists in valid_accounts Javascript obj
                form_elem = document.getElementById("acc_management");
                form_elem.submit();
            }
            else{
                err_msg_tag = document.getElementById("err_msg");
                err_msg_tag.textContent = "Invalid Account Number! User does not own this account";
            }
            */
         }
         
         
         </script>
        
    {% endblock%}
    
    </body>

BankingProject-main/final/profiles/templates/profiles/deposit.html
<body>
    {% extends 'base.html' %}
    {% load static %}
    
    {% block stylecontent %}
        <style>
            body {
                background-color: aliceblue;
            }
            h2 {
                font-family: 'Slabo 27px';
                border-bottom: 1px solid black;
                font-weight: 900;
            }
            #page_name {
                font-size: 25;
            }
            
            #details_box {
                font-size: 23;
                top: 50px;
                left: 30px;
            }
            
            #details_table {
                font-size: 20;
                position: relative;
                align-items: center;
            }
            
            #edit_details {
                top: 10px;
                left: 20px;
            }
            
            #edit_button {
                border: none;
                color: black;
                padding: 5px 7px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 14px;
                margin: 2px 1px;
                cursor: pointer;
            }
        </style>
    {%endblock%}
    
    {% block bodycontent %}
        <table width=70% height=60%>
            <tr>
                <td>
                    <div id="page_name" style="float:left;">
                        <font color="#3399ff">Deposit</font>
                    </div>
                </td>
                <td>
                    <div id="edit_details" style="float:right;">
                        <button type="button" id="edit_button"><a href="{% url 'profiles:dashboard' %}">Home</a></button>
                    </div>
                    
                </td>
                
            </tr>
            <tr>
                <td></td>

                <td>

                    <div id="details_box">
                        <form name="deposit_details" action="deposit" method="POST">
                            <table id="details_table" cellpadding=5px;>
                                {% if accounts %}
                               {% csrf_token %}
                                <tr>
                                    <td>Amount to be deposited :</td>
                                    <td><input type="text" name="amount" placeholder="Amount"></td>
                                </tr>
                                <tr>
                                    <td> Deposit into account :</td>
                                    <td><input type="text" name="acc_no" placeholder="Account number"></td>
                                </tr>

                                <tr>
                                    <td></td>
                                    <!--<td><input type="button" value="Withdraw"></td>-->
                                    <td><button>Deposit</button></td>
                                </tr>
                                {% else %}
                                    <tr> <td> New Customer. No accounts yet. </td></tr>
                                {% endif %}
                                <tr>
                                    <td><span>{{msg|safe}}</span></td>
                                </tr>
                                <tr>
                                    <td> <small>By transferring money from your account, you agree to the <a href="#">Terms and Conditions</a> of amount transfer</small>. <br></td>
                                </tr>
                            </table>
                        </form>
                    </div>
                </td>
            </tr>
        </table>
    {%endblock%}
</body>

</html>

BankingProject-main/final/profiles/templates/profiles/ecs.html
{% extends 'base.html' %}
    
    {% block stylecontent %}
    <style>
        body {
            background-color: aliceblue;
        }
        h2 {
            font-family: 'Slabo 27px';
            border-bottom: 1px solid black;
            font-weight: 900;
        }
        #page_name {
            font-size: 25;
        }
        
        #details_box {
            font-size: 23;
            top: 50px;
            left: 30px;
        }
        
        #details_table {
            font-size: 20;
            position: relative;
            align-items: center;
        }
        
        #edit_details {
            top: 10px;
            left: 20px;
        }
        
        #edit_button {
            border: none;
            color: black;
            padding: 5px 7px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 14px;
            margin: 2px 1px;
            cursor: pointer;
        }
    </style>
    {%endblock%}
    
<body>
    {% block bodycontent %}
    <table width=70% height=60%>
        <tr>
            <td>

                <div id="page_name" style="float:left;">
                    <font color="#3399ff">User account</font>
                </div>
            </td>
            <td>
                <div id="edit_details" style="float:right;">
                    <button type="button" id="edit_button"><a href="{% url 'profiles:dashboard' %}">Home</a></button>
                </div>
            </td>
        </tr>
    </table>
    <form name="ecs_opt" action="redirect_ecs">
    <input type="hidden" name="ecs_option" id="ecs_option">
    <button class="button" onclick="set_ecs_option('new_ecs')"> Set Up New ECS </button>
    <button class="button" onclick="set_ecs_option('view_ecs')"> Pay Biller </button>
    </form>
    
    <script>
        function set_ecs_option(option){
            hidden_field = document.getElementById("ecs_option");
            hidden_field.setAttribute("value", option);
        }
    </script>
    {% endblock%}
</body>

</html>

BankingProject-main/final/profiles/templates/profiles/ecs_show_bills.html
{% extends 'base.html' %}
    
    {% block stylecontent %}
    <style>
        body {
            background-color: aliceblue;
        }
        h2 {
            font-family: 'Slabo 27px';
            border-bottom: 1px solid black;
            font-weight: 900;
        }
        #page_name {
            font-size: 25;
        }
        
        #details_box {
            font-size: 23;
            top: 50px;
            left: 30px;
        }
        
        #details_table {
            font-size: 20;
            position: relative;
            /*align-items: center;*/
            align-items: left;
        }
        
        #edit_details {
            top: 10px;
            left: 20px;
        }
        
        #edit_button {
            border: none;
            color: black;
            padding: 5px 7px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 14px;
            margin: 2px 1px;
            cursor: pointer;
        }
    </style>
    {%endblock%}
    <body>
    {% block bodycontent %}

    <form name="pay_bills" action="pay_bill">
    <table width=70% height=60%>
    <!-- table width=100% height=60% -->
        <tr>
            <td>

                <div id="page_name" style="float:left;">
                    <font color="#3399ff">User account</font>
                </div>
            </td>
            <td>
                <div id="edit_details" style="float:right;">
                    <button type="button" id="edit_button"><a href="{% url 'profiles:dashboard' %}">Home</a></button>
                </div>
            </td>
        </tr>



        <tr>
            <td>
                <div id="details_box" align="center">
                    <h4>Bills to be paid :</h4>
                    <input type="hidden" name="bill_id" id="bill_id">
                    <table id="details_table" cellpadding=5px; width="100%">

                        <tr>



                        </tr>
                        <tr>
                            <!-- td> </td -->

                        </tr>
                        <tr>
                            <th colspan=""> Bill ID </th>
                            <th colspan=""> Biller Name </th>
                            <th colspan=""> Account <br> number </th>
                            <!-- th colspan=""> Bills </th -->

                            <th colspan=""> Amount </th>
                            <th colspan=""> Upper Limit </th>
                            <th colspan=""> Within Limit? </th>
                            <th colspan=""> Pay </th>

                        </tr>
                        {% for bill in bills_list %}
                        <tr>
                            <!--td> </td -->
                            {% for detail in bill %}
                            <td> {{detail}} </td>
                            {% endfor %}
                            
                            <!-- td> {{ bill.Amount }} </td>
                            <!-- td> </td -->
                            <td>
                                <div id="pay_bill" style="float:right;">
                                    <button type="submit" id="edit_button" onclick="set_bill_id({{ bill|first }})">Pay Bill</button>
                                </div>
                            </td>
                            
                            

                        </tr>
                        {% endfor %}
                        <!--
                        <tr>
                            <td> </td>
                            <td> </td>
                            <td> </td>
                            <td> </td>
                            <td>
                                <div id="pay_bill" style="float:right;">
                                    <button type="button" id="edit_button">Pay Bill</button>
                                </div>
                            </td>

                        </tr>

                        <tr>
                            <td> </td>
                            <td> </td>
                            <td> </td>
                            <td> </td>
                            <td>
                                <div id="pay_bill" style="float:right;">
                                    <button type="button" id="edit_button">Pay Bill</button>
                                </div>
                            </td>

                        </tr>
                        -->


                    </table>
                </div>
            </td>
        </tr>
    </table>
     </form>
    <script>
        function set_bill_id(bill_id){
            hidden_field = document.getElementById("bill_id");
            hidden_field.setAttribute("value", bill_id);
            console.log(hidden_field);
         }
    </script>
    {% endblock%}
</body>

BankingProject-main/final/profiles/templates/profiles/successful_new_ecs.html
<b>
New ECS was created successfully!
</b>