BankingProject-main/final/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = "accounts"

urlpatterns = [
    url(r"^register/$", views.register, name = "signup"),
    url(r"^login/$", views.sign_in, name = "signin"),
    url(r"^logout/$", views.logout_view, name = "logout"),
]

BankingProject-main/final/bank/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from accounts import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^accounts/', include("accounts.urls")),
    url(r'^profiles/', include("profiles.urls"))
]

BankingProject-main/final/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>Online Bank</title>
        
       
        {% block stylecontent %}

        {% endblock %}
        

    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
            <!--<a class="navbar-brand"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon">icon</span>
            </button>-->
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{% url 'accounts:signup' %}" id="nav-create">Create new account</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:signin' %}" id="nav-login">SignIn</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:signin' %}" id="nav-login">Logout</a>
                </div>
            </div>
        </nav>
        
        <br> <br> <br>
         <!-- diffrent contents rendered here-->
        {% block bodycontent %}

        {% endblock %}

        {% block scriptcontent %}
        {% endblock %}
        
    </body>
</html>